plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*_*.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'storage/**/*'
    - 'public/**/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'test/**/*'
    - 'Gemfile'
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Rails:
  Enabled: true

Rails/I18nLocaleTexts:
  Enabled: false

Minitest/MultipleAssertions:
  Max: 10

Minitest/AssertPredicate:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - 'test/fixtures/**/*'

Lint/UselessConstantScoping:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*'
